import io
import zipfile

def create_zip(backend_files, frontend_files, product_name, description, marketing_copy):
    """
    Creates an in-memory ZIP archive of the generated project.
    
    Structure:
    - README.md (Root explanation, run instructions, and marketing details)
    - backend/ (FastAPI backend files)
    - frontend/ (Next.js/React frontend files)
    """
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Retrieve custom README generated by MarketingAgent, or generate fallback
        readme_content = marketing_copy.get("readme")
        if not readme_content:
            # Fallback README template
            readme_content = f"""# {product_name}

{description}

Generated automatically by VibeDeploy.

## Technology Stack

- **Backend**: FastAPI (Python)
- **Frontend**: Next.js (React + Tailwind CSS)
- **Database**: SQLite / PostgreSQL (configured via SQLAlchemy)

---

## Getting Started

### 1. Run the Backend
```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```
The API documentation will be available at [http://127.0.0.1:8000/docs](http://127.0.0.1:8000/docs).

### 2. Run the Frontend
```bash
cd frontend
npm install
npm run dev
```
The web app will be running at [http://localhost:3000](http://localhost:3000).

---

## Marketing & Copywriting Strategy

### Headline
**"{marketing_copy.get('hero_headline', '')}"**

### Subheadline
"{marketing_copy.get('hero_subheadline', '')}"

### Key Value Propositions
{chr(10).join(f"- {bullet}" for bullet in marketing_copy.get('copywriting_bullets', []))}

### Suggested Pricing Tiers
"""
            pricing = marketing_copy.get('pricing_tiers', [])
            for tier in pricing:
                readme_content += f"\n#### {tier.get('name', 'Tier')} - {tier.get('price', '$0')}\n"
                readme_content += f"- **Target**: {tier.get('target', '')}\n"
                readme_content += f"- **Features**:\n"
                for feat in tier.get('features', []):
                    readme_content += f"  - {feat}\n"
                    
            readme_content += "\n---\n*VibeDeploy: Describe and Deploy SaaS.*"
        
        # Write README.md to root
        zip_file.writestr("README.md", readme_content)
        
        # Write backend files
        for filename, content in backend_files.items():
            # Ensure folder hierarchy
            zip_file.writestr(f"backend/{filename}", content)
            
        # Write frontend files
        for filename, content in frontend_files.items():
            zip_file.writestr(f"frontend/{filename}", content)
            
    zip_buffer.seek(0)
    return zip_buffer.getvalue()
